[tool.poetry]
name = "capturejob"
version = "0.3.1"
description = "A library to capture job outputs to persistent storage"
authors = ["aurecon"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.5.3"
dyndebug = "^0.2.0"
azure-storage-blob = "^12.9.0"
dotmap = "^1.3.26"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
dotmap = "^1.3.25"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "capturejob.main:main"
test = "pytest:main"
