
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-10T22:25:54-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ab08dea1e70e7ecbac65ae1dead415f95e8360d",
 "version": "2.5.1.dev20220312"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
