[tool.poetry]
name = "synapse-lib"
version = "0.1.0"
description = "Lorem Ipsum"
authors = ["Dieter Buehler"]
packages = [     { include = "src" }, ]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
