
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T15:35:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce67d9b7697b2884bfc691c32dbcf3d4ccef12c7",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
