
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-13T02:17:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c0d89cb7c774cba53242b9a3981fd02e75f3902",
 "version": "0.9.dev2211"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
