
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-15T13:28:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a70a77e94b5f6ddaa759e802c07bb771ffa2f8a",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
