[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "btjanaka"
version = "0.4.0"
description = "Bryon Tjanaka in a Python package!"
authors = ["Bryon Tjanaka <bryon@btjanaka.net>"]
license = "MIT"
readme = "README.md"
homepage = "https://btjanaka.net"
repository = "https://github.com/btjanaka/btjanaka-pypi"
keywords = ["fun", "awesome"]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Utilities",
]
exclude = ["setup.cfg"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
isort = "^5.6.4"
yapf = "^0.30.0"
pylint = "^2.6.0"
pytest = "7.0.1"
pytest-cov = "3.0.0"
bump2version = "0.5.11"
check-wheel-contents = "^0.2.0"

[tool.pytest.ini_options]
addopts = "-v --cov-report term-missing --cov=btjanaka tests/"
