[project]
name = 'pylandau'
version = '2.2.0'
description = 'A Landau PDF definition to be used in Python.'
repository = 'https://github.com/SiLab-Bonn/pyLandau'
license = 'LGPL-2.1-only'
python = '^3.8'
readme = 'README.md'
authors = 'David-Leon Pohl, Christian Bespin'
maintainers  ='David-Leon Pohl, Christian Bespin'
author_email = 'pohl@physik.uni-bonn.de, bespin@physik.uni-bonn.de'
maintainer_email = 'pohl@physik.uni-bonn.de, bespin@physik.uni-bonn.de'

[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "numpy>=1.22",
    "cython>=0.29",
]  # PEP 508 specifications
build-backend = "setuptools.build_meta"
