[tool.poetry]
name = "kvom"
version = "0.2.0"
description = "key-value store object mapping"
authors = ["ischaojie <zhuzhezhe95@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.9.0"
redis = "^4.1.3"
pymongo = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
black = "^22.1.0"
mypy = "^0.931"
pytest-cov = "^3.0.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
pytest-xdist = "^2.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
