[tool.poetry]
name = "django-semantic-admin"
version = "0.3.2"
description = "Django Semantic UI Admin theme"
authors = ["Alex <globophobe@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/globophobe/django-semantic-admin"
repository = "https://github.com/globophobe/django-semantic-admin"
keywords = ["django", "admin", "theme"]
classifiers = ["Framework :: Django", "Development Status :: 4 - Beta", "Operating System :: OS Independent"]
packages = [{ include = "semantic_admin" }]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
django = ">=3.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
isort = "^5.7.0"
Pillow = "^9.0.0"
django-taggit = "^1.3.0"
django-filter = "^2.4.0"
invoke = "^1.5.0"
factory-boy = "^3.2.0"
Faker = ">=8.9.1"
gunicorn = "^20.0.4"
whitenoise = "^5.2.0"
mkdocs = "^1.1.2"
python-decouple = "^3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
