[tool.poetry]
name = "hub-scraper"
version = "0.6.1"
description = "Tool to grab articles from the habr.com hubs."
packages = [{include="hub_scraper"}]
authors = ["Dmitrii Kurlov <dmitriik@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/dmitriiweb/hub-scraper"
keywords = ["habr.com", "scraper", "cli", "tools"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
click = "^8.0.4"
pydantic = "^1.9.0"
httpx = "^0.22.0"
loguru = "^0.6.0"
lxml = "^4.8.0"
chompjs = "^1.1.6"
aiofile = "^3.7.4"
markdownify = "^0.10.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
tox = "^3.24.5"
mkdocs-material = "^8.1.7"
mkdocstrings = "^0.17.0"
pre-commit = "^2.17.0"
black = "^21.12b0"
isort = "^5.10.1"
mypy = "^0.931"
flake8 = "^4.0.1"
pytest-asyncio = "^0.17.2"

[tool.poetry.scripts]
hub-scraper = "hub_scraper.console.application:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
force_single_line = false
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
src_paths = ["hub_scraper", "tests"]
skip_glob = ["*/setup.py"]
filter_files = true
known_first_party = "hub_scraper"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''

[tool.mypy]
mypy_path = "hub_scraper"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
