[tool.poetry]
name = "mpk"
version = "0.1.0.alpha6"
description = "Media Programming Kit Python bindings"
authors = [ "ellis <ellis@rwest.io>" ]
license = "WTFPL"
repository = "https://hg.rwest.io/mpk"
keywords = ["media", "Rust", "FFI", "audio"]
include = ["main.py"]
[tool.poetry.dependencies]
numpy = ">=1.21.5,<1.22"
essentia = "2.1b6.*"
librosa = "^0.9.1"
python = "3.9"

[tool.poetry.dev-dependencies]
black = {version = ">=21", python = ">=3.9"}

[tool.poetry.scripts]
main = "main:run"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'