#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class ResourceTypeRelationshipOrderField(Enum):
    RESOURCE_TYPE_A = "RESOURCE_TYPE_A"
    RESOURCE_TYPE_B = "RESOURCE_TYPE_B"
    LOCATION_TYPE = "LOCATION_TYPE"
    RESOURCE_RELATIONSHIP_TYPE = "RESOURCE_RELATIONSHIP_TYPE"
    RESOURCE_RELATIONSHIP_MULTIPLICITY = "RESOURCE_RELATIONSHIP_MULTIPLICITY"
    CREATED_AT = "CREATED_AT"
    UPDATED_AT = "UPDATED_AT"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "ResourceTypeRelationshipOrderField":
        return cls.MISSING_ENUM
