
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T13:35:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0eb66d7fa928ef7eb723a8ee92eba6ba60834394",
 "version": "0.0.67.post0.dev324"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
