[build-system]
requires = ["setuptools>=43.0.0",
            "setuptools_scm>=6.2",
            "wheel"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "extension_helpers/version.py"
