#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class ResourceRelationshipFilterType(Enum):
    RESOURCE_RELATIONSHIP_LOCATION = "RESOURCE_RELATIONSHIP_LOCATION"
    RESOURCE_RELATIONSHIP_RESOURCE = "RESOURCE_RELATIONSHIP_RESOURCE"
    RESOURCE_RELATIONSHIP_TYPES = "RESOURCE_RELATIONSHIP_TYPES"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "ResourceRelationshipFilterType":
        return cls.MISSING_ENUM
