#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class ResourceRelationshipTypeKind(Enum):
    BELONGS_TO = "BELONGS_TO"
    LOCATED_IN = "LOCATED_IN"
    PHYSICAL_LINK = "PHYSICAL_LINK"
    LOGICAL_LINK = "LOGICAL_LINK"
    CROSS_CONNECTION = "CROSS_CONNECTION"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "ResourceRelationshipTypeKind":
        return cls.MISSING_ENUM
