[project]
name = "pybuild"
version = "0.0.1"
description = "Python src+dependency bundler."
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
