# Generated by Django 2.2.27 on 2022-02-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCheckboxes',
        ),
        migrations.DeleteModel(
            name='QuestionCheckboxesProposition',
        ),
        migrations.DeleteModel(
            name='QuestionFreeText',
        ),
        migrations.DeleteModel(
            name='QuestionMultipleChoice',
        ),
        migrations.DeleteModel(
            name='QuestionMultipleChoiceProposition',
        ),
        migrations.DeleteModel(
            name='QuestionRadio',
        ),
        migrations.DeleteModel(
            name='QuestionRadioProposition',
        ),
        migrations.DeleteModel(
            name='QuestionRange',
        ),
        migrations.DeleteModel(
            name='QuestionSingleChoice',
        ),
        migrations.DeleteModel(
            name='QuestionSingleChoiceProposition',
        ),
    ]
