[tool.poetry]
name = "chime-frb-api"
version = "2022.3.17"
description = "CHIME/FRB API"
authors = ["Shiny Brar <charanjotbrar@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/CHIMEFRB/frb-api"
documentation = "https://github.com/CHIMEFRB/frb-api"
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
	"Intended Audience :: Education",
	"Intended Audience :: Science/Research",
	"Topic :: Scientific/Engineering :: Astronomy",
	"Topic :: Software Development :: Libraries :: Python Modules",
	"License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9"
]

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0.0"
requests = "^2.22"
pyjwt = ">=1.7"
python-dateutil = "^2.8"
mkdocstrings = {version = "^0.16.2", optional = true}
pytkdocs = {version = ">=0.10", optional = true, extras = ["numpy-style"]}
mkdocs-material = {version = "^7.3.6", optional = true}
attrs = "^21.2.0"

[tool.poetry.dev-dependencies]
pytest = "^4.5"
pytest-cov = "^2.7"
coverage = "^4.5"
coveralls = "PyYaml"
pyyaml = "^5.1"
docker = "^5.0.0"
pre-commit = "^2.16.0"
black = "^22.1.0"

[tool.poetry.extras]
docs = ["mkdocs-material", "mkdocstrings", "pytkdocs"]


[tool.commitizen]
name = "cz_conventional_commits"
version = "2022.3.1"
tag_format = "$version"
version_files = ["pyproject.toml:version"]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
