
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T21:40:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b87ea0740425e56915705c4e6a9a6e0ac5b39bc",
 "version": "0.0.67.post0.dev308"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
