# Generated by Django 2.2.27 on 2022-03-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0004_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseitemscale',
            name='scale',
            field=models.IntegerField(null=True),
        ),
    ]
