[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
]

[tool.semantic_release]
    version_variable = [
        'setup.py:__version__'
    ]
    changelog_file = "CHANGELOG.md"
    branch = "master"
    version_source = "tag"
    patch_without_tag = true
    hvcs = "gitlab"
    build_command = "pip install build && python -m build"

