name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pypa/build
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: Build a binary wheel and a source tarball
        run: make build

      - name: Publish distribution to Test PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: make distribute-test

      - name: Publish distribution to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        if: startsWith(github.ref, 'refs/tags')
        run: make distribute
