[tool.poetry]
name = "insight-engine-schema-python"
version = "0.3.21"
description = "Rialtic insight engine schema in Python"
authors = ["Rialtic <engines.data@rialtic.io>"]

license = "Apache-2.0"
readme = "README.md"
homepage = "https://rialtic.io"
repository = "https://github.com/rialtic-community/insight-engine-schema-python"
keywords = ["rialtic", "insight", "engines", "schema"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "schema" }
]

[tool.poetry.dependencies]
python = "^3.7"
"fhir.resources" = "^6.0"

[tool.poetry.dev-dependencies]
pytest = ">= 6.2.2"
mypy = ">= 0.800"
pytest-mypy = ">= 0.8.0"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "nexus_downstream"
url = "https://artifacts.services.rialtic.dev/repository/libraries-group-python/simple/"
default = true
