
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-15T07:01:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "12d53e2e567eef5a28cce69c38251a20682e904f",
 "version": "0.0.76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
