[tool.poetry]
name = "skytop"
version = "0.1.0"
description = ""

license = "MIT"

authors = ["SkyTop"]

readme = "README.md"

repository = "https://github.com/SkyTopCo/skytop-py"
homepage = "https://www.sky.top/"

[tool.poetry.dependencies]
python = "^3.7"
requests = "2.27.1"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
pytest-asyncio = "0.17.2"
pytest-env = "0.6.2"
pytest-flake8 = "1.0.7"
