[tool.poetry]
name = "janda"
version = "1.0.11"
description = ""
authors = ["sinkaroid <anakmancasan@gmail.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pdoc = "^10.0.3"