[tool.poetry]
name = "get-repo"
version = "0.1.2"
repository = "https://github.com/florian42/get-repo"
description = "Small cli utility for cloning git repos in an orderly manner"
readme = "README.md"
authors = ["Florian <hey@flo.fish>"]
license = 'MIT'

[tool.poetry.scripts]
get-repo = "get_repo.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.4.0"
git-url-parse = "^1.2.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pre-commit = "^2.17.0"
flake8-bugbear = "^22.1.11"
flake8-eradicate = "^1.2.0"
flake8-functions-names = "^0.3.0"
flake8-variables-names = "^0.0.5"
flake8-builtins = "^1.5.3"
isort = "^5.10.1"
mypy = "^0.940"
bumpversion = "^0.6.0"
twine = "^3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
