[tool.poetry]
name = "boeah"
version = "0.1.2"
description = "Boeah Framework"
authors = ["Fathur <hi.fathur.rohman@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.1.2"
rich = "^11.2.0"
Werkzeug = "^2.0.3"
ipython = "^7.32"

[tool.poetry.dev-dependencies]
watchdog = "^2.1.6"
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
