[tool.poetry]
name = "pytm"
version = "1.2.1"
description = "A Pythonic framework for threat modeling"
authors = ["pytm Team"]
license = "MIT License"
readme = "README.md"
homepage = "https://owasp.org/www-project-pytm/"
repository = "https://github.com/izar/pytm"
keywords = ["security", "threat modeling", "risk"]
classifiers = [ "Development Status :: 5 - Production/Stable",
"Intended Audience :: Education",
"Operating System :: MacOS",
"License :: OSI Approved :: MIT License",
"Programming Language :: Python :: 3",
]
include = [ "LICENSE", ]

[tool.poetry.dependencies]
python = "^3.9 || ^3.8 || ^3.7 || ^3.6"
pydal = "~20200714.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
