
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T04:26:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a43779b55e1f5e8fc869665058e38e18952407f",
 "version": "1.16.0.post.dev274"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
