[tool.poetry]
name = "whale_back_bone"
version = "1.1.0"
description = " This library is aimed to create a MySQL connector that could be used by the 4th Whale Marketing data team."
authors = ["Arnaud Pourchez <arnaud.pourchez@hotmail.fr>"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^1.4.32"
PyMySQL = "^1.0.2"
pandas = "^1.3.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.masonry.api"
