
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T18:20:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "639ed96b0795249b24c7b52bf5fd4e85c7aad395",
 "version": "0.0.69"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
