
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T11:10:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "20bea3332d46e3789b1271142c941c8123fa14ea",
 "version": "0.7.1.post.dev431"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
