
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T14:36:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea8d1b5c16c1c1a6ef7742649a934e0fa0fa5e92",
 "version": "0.1.2rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
