[[bench]]
harness = false
name = "store"

[dependencies]
digest = "0.10"
hex = "0.4"
lazy_static = "1"
md-5 = "0.10"
nom = "7"
oxilangtag = "0.1"
oxiri = "0.2"
rand = "0.8"
regex = "1"
rio_api = "0.7"
rio_turtle = "0.7"
rio_xml = "0.7"
sha-1 = "0.10"
sha2 = "0.10"
siphasher = "0.3"
sysinfo = "0.23"

[dependencies.oxrdf]
features = ["rdf-star"]
path = "../oxrdf"
version = "0.1.0-rc.1"

[dependencies.sparesults]
features = ["rdf-star"]
path = "../sparesults"
version = "0.1.0-rc.1"

[dependencies.spargebra]
features = ["rdf-star"]
path = "../spargebra"
version = "0.2.0-rc.1"

[dev-dependencies]
criterion = "0.3"
oxhttp = "0.1"
zstd = "0.10"

[features]
default = []
http_client = ["oxhttp", "oxhttp/rustls"]

[package]
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
categories = ["database-implementations"]
description = "a SPARQL database and RDF toolkit\n"
edition = "2021"
homepage = "https://oxigraph.org/"
keywords = ["RDF", "SPARQL", "graph-database", "database"]
license = "MIT OR Apache-2.0"
name = "oxigraph"
readme = "README.md"
repository = "https://github.com/oxigraph/oxigraph/tree/master/lib"
version = "0.3.0-rc.1"
[package.metadata.docs.rs]
all-features = true
[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
libc = "0.2"

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.oxhttp]
optional = true
version = "0.1"

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.oxrocksdb-sys]
path = "../oxrocksdb-sys"
version = "0.3.0-rc.1"
[target."cfg(target_arch = \"wasm32\")".dependencies]
js-sys = "0.3"

[target."cfg(target_arch = \"wasm32\")".dependencies.getrandom]
features = ["js"]
version = "0.2"

[target."cfg(target_arch = \"wasm32\")".dev-dependencies]
wasm-bindgen-test = "0.3"
