variables:
  DJANGO_SETTINGS_MODULE: django_burl.tests.settings
  BURL_SECRET_KEY: "opiuqweroiuqweporiuqweopiurqpwo872sdf23asxxfzg92w3457oialsfkjhsdf"
  BURL_POSTGRES_HOST: postgres
  POSTGRES_DB: burl
  POSTGRES_USER: burl
  POSTGRES_PASSWORD: burl
  POSTGRES_HOST_AUTH_METHOD: trust

default:
  image: python:3.10
  services:
    - postgres:14
  cache:
    paths:
      - ~/.cache/pip
  before_script:
    - apt -y update && apt -y install apt-utils postgresql-client libpq-dev
    - pip install psycopg2 pbr

wheel:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
  rules:
    - if: $CI_COMMIT_TAG

burl-tests:
  stage: test
  script:
    - pip install -e .
    - django-admin test -v3
