input: ["none"]
output: ["img", "pipeline_end", "filename", "saved_video_fps"]

# May need to change fps_saved_output_video depending on user machine
# performance and if threading and buffer_frames are both True.
# (see Threading technotes below)
fps_saved_output_video: 10
filename: webcamfeed.mp4
resize: {
            do_resizing: False,
            width: 1280,
            height: 720
        }
input_source: 0    # 0 for webcam, rtsp URL for CCTV
mirror_image: False
frames_log_freq: 100    # Logs frequency of frames passed in cli
# Threading technotes for input.live:
# 1. Enabling threading can speed up webcam FPS by 20-30%.
# 2. If threading is True, it is recommended that buffer_frames is False if only
#    output.screen is used.  Otherwise the onscreen video display could be laggy
#    due to the buffering.
# 3. Threading = True, buffer_frames = True is recommended when input.live is
#    paired with output.media_writer so as to ensure that all frames are output
#    and saved into the file (i.e. no lost frames).
#    In addition, fps_saved_output_video should be set to the framerate of the
#    input source, typically 25 or 30 fps for webcam, to ensure the saved video
#    is able to play back smoothly (e.g. no "teleporting" person).
threading: False
buffer_frames: False
