
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-14T17:05:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7392c1c68c5f845308a4ceb38f71d8c394ad04a2",
 "version": "2022.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
