---
name: upload

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build, check and upload distribution
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          make twine-upload
