---
subject:
  C:  NL
  ST: Zuid Holland
  L:  Alphen aan den Rijn
  O:  Mannem Solutions
  OU: Chainsmith TLS chain maker
  CN: chainsmith

#tmpdir: /tmp/certs/postgres

intermediates:
  - name: server
    servers: {}
# You can set servers directly
#      sscc-pgsdb-l01o:
#        - 131.224.65.66
# You can read servers from an environment
#    environment: environments/poc/hosts
  - name: client
    clients:
      - postgres
      - wal-g
      - application
