# Python plugin definition
refs:
    # TODO: Add base plugin reference
    - python.yml    # Python path contribution
    - action.yml    # Action generation

config:
    # Plugin version
    nmkGithubPluginVersion:
        __resolver__: nmk_github.NmkGithubVersionResolver

    # Plugin versions dict
    nmkPluginsVersions:
        nmk-github: ${nmkGithubPluginVersion}

    # Plugin help links dict
    nmkPluginsDocs:
        nmk-github: https://github.com/dynod/nmk/wiki/nmk-github-plugin
