
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-14T11:10:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f360fba591941989a59d30f7be3477e635433a48",
 "version": "2.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
