version: "2.4"

services:
  bitcoind:
    image: "${CI_REGISTRY:-registry.gitlab.com}/hashbeam/docker/bitcoind:22.0"
    logging:
      options:
        max-size: "77m"
        max-file: "7"
    cpu_quota: 100000
    cpu_shares: 128
    mem_limit: 1280000000
    memswap_limit: 1280000000
    restart: "unless-stopped"
    stop_grace_period: "3m"
    environment:
      MYUID: ${MYUID:-1000}
      MYGID: ${MYGID:-1000}
    ports:
      - 18443:18443
      - 18444:18444
      - 28333:28333
      - 28332:28332
    volumes:
      - blockchain:/srv/app/.bitcoin
  c-lightning:
    image: "${CI_REGISTRY:-registry.gitlab.com}/hashbeam/docker/c-lightning:0.10.1"
    logging:
      options:
        max-size: "77m"
        max-file: "7"
    cpu_quota: 100000
    cpu_shares: 128
    mem_limit: 1280000000
    memswap_limit: 1280000000
    restart: "unless-stopped"
    stop_grace_period: "3m"
    command: "--allow-deprecated-apis=false"
    environment:
      MYUID: ${MYUID:-1000}
      MYGID: ${MYGID:-1000}
      RGB: "CC0066"
    ports:
      - 9735:9735
      - 9835:9835
    volumes:
      - clightning_data:/srv/app/.lightning
  eclair:
    image: "${CI_REGISTRY:-registry.gitlab.com}/hashbeam/docker/eclair:0.6.2"
    logging:
      options:
        max-size: "77m"
        max-file: "7"
    cpu_quota: 100000
    cpu_shares: 128
    mem_limit: 1280000000
    memswap_limit: 1280000000
    restart: "unless-stopped"
    stop_grace_period: "3m"
    environment:
      MYUID: ${MYUID:-1000}
      MYGID: ${MYGID:-1000}
      RGB: "0066ff"
    ports:
      - 9736:9736
      - 8080:8080
    volumes:
      - eclair_data:/srv/app/data
  electrum:
    image: "${CI_REGISTRY:-registry.gitlab.com}/hashbeam/docker/electrum:4.1.5"
    logging:
      options:
        max-size: "77m"
        max-file: "7"
    cpu_quota: 100000
    cpu_shares: 128
    mem_limit: 1280000000
    memswap_limit: 1280000000
    restart: "unless-stopped"
    stop_grace_period: "3m"
    environment:
      MYUID: ${MYUID:-1000}
      MYGID: ${MYGID:-1000}
      WALLET_NAME: alice
      SRV_HOST: electrs
    volumes:
      - electrum_data:/srv/wallet
    ports:
      - 7777:7777
      - 9737:9737
  electrs:
    image: "${CI_REGISTRY:-registry.gitlab.com}/hashbeam/docker/electrs:0.9.5"
    logging:
      options:
        max-size: "77m"
        max-file: "7"
    cpu_quota: 100000
    cpu_shares: 128
    mem_limit: 1280000000
    memswap_limit: 1280000000
    restart: "unless-stopped"
    stop_grace_period: "3m"
    environment:
      MYUID: ${MYUID:-1000}
      MYGID: ${MYGID:-1000}
    ports:
      - 50001:50001
    volumes:
      - electrs_data:/srv/app/db
  lnd:
    image: "${CI_REGISTRY:-registry.gitlab.com}/hashbeam/docker/lnd:0.14.0-beta"
    logging:
      options:
        max-size: "77m"
        max-file: "7"
    cpu_quota: 100000
    cpu_shares: 128
    mem_limit: 1280000000
    memswap_limit: 1280000000
    restart: "unless-stopped"
    stop_grace_period: "3m"
    environment:
      MYUID: ${MYUID:-1000}
      MYGID: ${MYGID:-1000}
      NO_MACAROONS: 1
    hostname: "lnd"
    ports:
      - 9738:9738
      - 10009:10009
    volumes:
      - lnd_data:/srv/app/.lnd

volumes:
  blockchain:
    driver: local
  clightning_data:
    driver: local
  eclair_data:
    driver: local
  electrum_data:
    driver: local
  lnd_data:
    driver: local
  electrs_data:
    driver: local
