#Importing the necessary methods.
from Googlexcel_noPassword.Googlexcel_noPassword_v1 import fetch_sheetnameslist
from Googlexcel_noPassword.Googlexcel_noPassword_v1 import data_fromAllSheets
from Googlexcel_noPassword.Googlexcel_noPassword_v1 import data_OneSheet