
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-13T18:02:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "194e40576d44cdbfc05b5f508178c89662a41c4c",
 "version": "2.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
