
name: Documentation

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  docs:
    name: "Build Documentation"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"

      - name: "Install documentation requirements"
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r docs/requirements.txt
          python -m pip install -e .
      - name: "Create documentation"
        run: sh make_docs.sh
        working-directory: ./docs
