name: CI-Bridge

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.9.10'

    strategy:
      matrix:
        python-version: ["3.9.10"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '15'
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel pytest
          python -m pip install --upgrade  virtualenv
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-elicitation.txt
      - name: "Setting up environment"
        run: |
          export NEGMAS_IGNORE_TEST_NOTEBOOKS=True
          python -m pip install jupyter
          python3 -m ipykernel install --user
      - name: "Install negmas and geinus-bridge"
        run: |
          python -m pip install -e .
          negmas genius-setup
      - name: "running genius bridge"
        run: "java -jar ~/negmas/files/geniusbridge.jar --silent --no-logs &"
      - name: "Run pytest for ${{ matrix.python-version }}"
        run: |
          export NEGMAS_SLOW_TEST=True
          export NEGMAS_BRIDGE_OPS
          unset NEGMAS_BRIDGE_OPS
          export NEGMAS_IGNORE_TEST_NOTEBOOKS=True
          python -W ignore -m pytest tests/test_genius.py  || python -W ignore -m pytest --last-failed .
          python -W ignore -m pytest tests/test_inout.py  || python -W ignore -m pytest --last-failed .
          export NEGMAS_BRIDGE_OPS=True
          python -W ignore -m pytest tests/test_genius_bridge.py  || python -W ignore -m pytest --last-failed .
