name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.8.12", "3.9.10", "3.10.2"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel pytest
          python -m pip install --upgrade  virtualenv
          python -m pip install -r requirements.txt
      - name: "Setting up environment"
        run: |
          export NEGMAS_IGNORE_TEST_NOTEBOOKS=True
          python -m pip install jupyter
          python3 -m ipykernel install --user
      - name: "Run pytest for ${{ matrix.python-version }}"
        run: "export NEGMAS_IGNORE_TEST_NOTEBOOKS=True; python -W ignore -m pytest . || python -W ignore -m pytest --last-failed ."

  package:
    name: "Build & verify package"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"

      - name: "Install pep517 and twine"
        run: "python -m pip install --upgrade pip setuptools wheel pytest twine"
      - name: "Build package"
        run: "python setup.py sdist bdist_wheel"
      - name: "List result"
        run: "ls -l dist"
      - name: "Check long_description"
        run: "python -m twine check dist/*"

  install-dev:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    name: "Verify dev env"
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"
      - name: "Install in dev mode"
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r docs/requirements.txt
          python -m pip install -e .
      - name: "Import package"
        run: "python -c 'import negmas; print(negmas.__version__)'"
