[tool.poetry]
name = "class-composer"
version = "0.1.0"
description = "A library for making dataclasses"
authors = ["andy <andy.development@protonmail.com>"]
license = "MIT"

packages = [{include="composer"}]

[tool.poetry.dependencies]
python = "^3.9"
typing-extensions = "^4.1.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
pytest = "^6.2.5"
pytest-asyncio = "^0.17.0"
pytest-cov = "^3.0.0"
pre-commit = "^2.17.0"
isort = "^5.10.1"

[tool.black]
line-length = 90

[tool.isort]
profile = "black"

[tool.pyright]
typeCheckingMode = "strict"
reportImportCycles = false
reportUnnecessaryIsInstance = false
reportPrivateUsage = false
ignore = ["tests/"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
