[tool.poetry]
name = "pyconfmanager"
version = "1.0.0"
description = "Simple lib to read configs"
authors = ["Xenely"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
