
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-01T13:00:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0afd6c36811bcf0fe08fe3669317d5e9d7892f3",
 "version": "v1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
