[tool.poetry]
name = "nlhappy"
version = "0.1.11"
description = "一款致力于SOTA的中文自然语言处理库"
authors = ["wangmengdi <790990241@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.10.2"
pytorch-lightning = "^1.5.10"
transformers = "^4.16.2"
datasets = "^1.18.3"
oss2 = "^2.15.0"
spacy = "^3.2.2"
hydra-core = "^1.1.1"
jieba = "^0.42.1"
tqdm = "^4.63.0"
rich = "^12.0.0"
hydra-colorlog = "^1.1.0"
pkuseg = "^0.0.25"
scikit-learn = "^1.0.2"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."spacy_factories"]
"span_classifier" = "nlhappy.spacy_components:make_spancat"

[tool.poetry.scripts]
nlhappy = "nlhappy.run:train"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# 添加清华镜像
[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true