
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T14:49:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca11005c349546ed962bb1bbc4f66d8022ea79a1",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
