[tool.autopep8]
recursive = true
exclude = "./.venv/*"
max_line_length = 120
aggresive = 1
ignore = "E127"


[tool.isort]
# use black compatible settings
line_length = 120
multi_line_output = 3
include_trailing_comma = true
skip = [ ".tox", "dist", "node_modules" , ".venv", "build", ".git", "typings"]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"