
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T14:47:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8582e9e742701c9499aac79ea8ef68f95a663d90",
 "version": "0.15.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
