[tool.poetry]
name = "prometheus-query-builder"
version = "0.1.1"
description = "Package for generation Prometheus Query Language queries."
authors = ["Michail Tsyganov <tsyganov.michail@yandex.ru>"]
homepage = "https://github.com/m-chrome/prometheus-query-builder"
repository = "https://github.com/m-chrome/prometheus-query-builder"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
