[tool.poetry]
name = "quantumsymmetry"
version = "0.1.5"
description = "Quantum computing research package"
authors = ["Dario Picozzi"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.22.3"
pyscf = "^2.0.1"
openfermion = "^1.3.0"
qiskit = "^0.34.2"
ipython = "^7"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "poetry build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = true                    # patch release by default

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
