
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T14:30:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "93fd14e2d5f1db0eebf4fb9fb51156d29e70c27a",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
