
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T16:52:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "71967459471592e59d39e418b2aed6bce50a1ef1",
 "version": "0.9.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
