
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fa2c4680cca0d1d6b46e6c1ed68ceea4d9b79afb",
 "version": "1.8.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
