
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-12T18:28:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "feb92b4f0216c9e2c614eeb827c3398f5b448343",
 "version": "0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
