#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class ResourceTypeRelationshipFilterType(Enum):
    RESOURCE_RELATIONSHIP_MULTIPLICITY = "RESOURCE_RELATIONSHIP_MULTIPLICITY"
    RESOURCE_RELATIONSHIP_LOCATION_TYPE = "RESOURCE_RELATIONSHIP_LOCATION_TYPE"
    RESOURCE_RELATIONSHIP_TYPE = "RESOURCE_RELATIONSHIP_TYPE"
    RESOURCE_RELATIONSHIP_RESOURCE = "RESOURCE_RELATIONSHIP_RESOURCE"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "ResourceTypeRelationshipFilterType":
        return cls.MISSING_ENUM
