[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py39']
line-length = 79
exclude = '''
(
 /(
 \.eggs
 | \.git
 | \.mypy_cache
 | build
 | dist
 )/
)
'''
