
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-13T17:14:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "71e40fb6f587cf9401013a2449e442ae244df727",
 "version": "v1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
