# coding: utf-8

"""
    BIMData API

    BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@bimdata.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from bimdata_api_client.configuration import Configuration


class Extensions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'topic_type': 'list[str]',
        'topic_status': 'list[str]',
        'topic_label': 'list[str]',
        'priority': 'list[str]',
        'stage': 'list[str]',
        'user_id_type': 'list[str]',
        'priority_colors': 'list[str]',
        'topic_status_colors': 'list[str]'
    }

    attribute_map = {
        'topic_type': 'topic_type',
        'topic_status': 'topic_status',
        'topic_label': 'topic_label',
        'priority': 'priority',
        'stage': 'stage',
        'user_id_type': 'user_id_type',
        'priority_colors': 'priority_colors',
        'topic_status_colors': 'topic_status_colors'
    }

    def __init__(self, topic_type=None, topic_status=None, topic_label=None, priority=None, stage=None, user_id_type=None, priority_colors=None, topic_status_colors=None, local_vars_configuration=None):  # noqa: E501
        """Extensions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._topic_type = None
        self._topic_status = None
        self._topic_label = None
        self._priority = None
        self._stage = None
        self._user_id_type = None
        self._priority_colors = None
        self._topic_status_colors = None
        self.discriminator = None

        if topic_type is not None:
            self.topic_type = topic_type
        if topic_status is not None:
            self.topic_status = topic_status
        if topic_label is not None:
            self.topic_label = topic_label
        if priority is not None:
            self.priority = priority
        if stage is not None:
            self.stage = stage
        if user_id_type is not None:
            self.user_id_type = user_id_type
        self.priority_colors = priority_colors
        self.topic_status_colors = topic_status_colors

    @property
    def topic_type(self):
        """Gets the topic_type of this Extensions.  # noqa: E501


        :return: The topic_type of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._topic_type

    @topic_type.setter
    def topic_type(self, topic_type):
        """Sets the topic_type of this Extensions.


        :param topic_type: The topic_type of this Extensions.  # noqa: E501
        :type: list[str]
        """

        self._topic_type = topic_type

    @property
    def topic_status(self):
        """Gets the topic_status of this Extensions.  # noqa: E501


        :return: The topic_status of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._topic_status

    @topic_status.setter
    def topic_status(self, topic_status):
        """Sets the topic_status of this Extensions.


        :param topic_status: The topic_status of this Extensions.  # noqa: E501
        :type: list[str]
        """

        self._topic_status = topic_status

    @property
    def topic_label(self):
        """Gets the topic_label of this Extensions.  # noqa: E501


        :return: The topic_label of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._topic_label

    @topic_label.setter
    def topic_label(self, topic_label):
        """Sets the topic_label of this Extensions.


        :param topic_label: The topic_label of this Extensions.  # noqa: E501
        :type: list[str]
        """

        self._topic_label = topic_label

    @property
    def priority(self):
        """Gets the priority of this Extensions.  # noqa: E501


        :return: The priority of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this Extensions.


        :param priority: The priority of this Extensions.  # noqa: E501
        :type: list[str]
        """

        self._priority = priority

    @property
    def stage(self):
        """Gets the stage of this Extensions.  # noqa: E501


        :return: The stage of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._stage

    @stage.setter
    def stage(self, stage):
        """Sets the stage of this Extensions.


        :param stage: The stage of this Extensions.  # noqa: E501
        :type: list[str]
        """

        self._stage = stage

    @property
    def user_id_type(self):
        """Gets the user_id_type of this Extensions.  # noqa: E501


        :return: The user_id_type of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._user_id_type

    @user_id_type.setter
    def user_id_type(self, user_id_type):
        """Sets the user_id_type of this Extensions.


        :param user_id_type: The user_id_type of this Extensions.  # noqa: E501
        :type: list[str]
        """

        self._user_id_type = user_id_type

    @property
    def priority_colors(self):
        """Gets the priority_colors of this Extensions.  # noqa: E501

        Non standard field. Arrays of priorities and this array are in the same order.  # noqa: E501

        :return: The priority_colors of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._priority_colors

    @priority_colors.setter
    def priority_colors(self, priority_colors):
        """Sets the priority_colors of this Extensions.

        Non standard field. Arrays of priorities and this array are in the same order.  # noqa: E501

        :param priority_colors: The priority_colors of this Extensions.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and priority_colors is None:  # noqa: E501
            raise ValueError("Invalid value for `priority_colors`, must not be `None`")  # noqa: E501

        self._priority_colors = priority_colors

    @property
    def topic_status_colors(self):
        """Gets the topic_status_colors of this Extensions.  # noqa: E501

        Non standard field. Arrays of statuses and this array are in the same order.  # noqa: E501

        :return: The topic_status_colors of this Extensions.  # noqa: E501
        :rtype: list[str]
        """
        return self._topic_status_colors

    @topic_status_colors.setter
    def topic_status_colors(self, topic_status_colors):
        """Sets the topic_status_colors of this Extensions.

        Non standard field. Arrays of statuses and this array are in the same order.  # noqa: E501

        :param topic_status_colors: The topic_status_colors of this Extensions.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and topic_status_colors is None:  # noqa: E501
            raise ValueError("Invalid value for `topic_status_colors`, must not be `None`")  # noqa: E501

        self._topic_status_colors = topic_status_colors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Extensions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Extensions):
            return True

        return self.to_dict() != other.to_dict()
