
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T19:08:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6518b20cf3e0d1563fd1e05cd685ee188d4d8179",
 "version": "3.0.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
