[tool.poetry]
name = "metaDMG"
version = "0.20.5"
description = "metaDMG: Estimating ancient damage in (meta)genomic DNA rapidly"
authors = ["Christian Michelsen <christianmichelsen@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "metaDMG", from = "src" }]
repository = "https://github.com/metaDMG/metaDMG/"


[tool.poetry.dependencies]
python = ">=3.9,<3.11"
typer = "^0.4.0"
click-help-colors = "^0.9.1"
PyYAML = "^6.0"
iminuit = "^2.9.0"
scipy = "^1.7.3"
numpyro = "^0.9.0"
joblib = "^1.1.0"
pyarrow = "^6.0.1"
logger-tt = "^1.7.0"
psutil = "^5.9.0"
numba = "^0.55.1"
pandas = "^1.4.0"
# scipy = { version = "^1.7.3", python = ">=3.9,<3.11" }

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
# can be installed as e.g. poetry install --extras "all"
metadmg-viz = {version = "^0.11.1", optional = true}

Sphinx = {version = "^4.4.0", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}
sphinxcontrib-napoleon = {version = "^0.7", optional = true}
sphinx-click = {version = "^3.1.0", optional = true}
myst-parser = {version = "^0.17.0", optional = true}
sphinx-autodoc-typehints = {version = "^1.17.0", optional = true}
sphinx-copybutton = {version = "^0.5.0", optional = true}
autodocsumm = {version = "^0.2.7", optional = true}
sphinx-book-theme = {version = "^0.2.0", optional = true}

[tool.poetry.extras]
viz = ["metaDMG-viz"]
docs = [
    "Sphinx",
    "sphinx-rtd-theme",
    "sphinxcontrib-napoleon",
    "sphinx-click",
    "myst-parser",
    "sphinx-autodoc-typehints",
    "sphinx-copybutton",
    "autodocsumm",
    "sphinx-book-theme",
    ]


[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
flake8 = "^4.0.1"
black = "^22.1.0"
ipykernel = "^6.8.0"
nbformat = "^5.1.3"
python-semantic-release = "^7.24.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
Pympler = "^1.0.1"
notebook = "^6.4.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
metaDMG = "metaDMG.cli:cli_main"

[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "pip install poetry && poetry build"  # build dists
dist_path = "dist/"                         # where to put dists
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
major_on_zero = false                       # keeps the major version at 0


# [tool.poe.tasks]
# clean = """
# # Multiline commands including comments work too. Unescaped whitespace is ignored.
# rm -rf .coverage
#        .mypy_cache
#        .pytest_cache
#        dist
#        ./**/__pycache__
# """
# format = "black ."  # strings are interpreted as commands by default
# _build = "poetry build"
# _publish = "poetry publish"
# version = { "shell" = "poetry version $(git describe --tags --abbrev=0)" }
# build = ["version", "_build"]
# release = ["clean", "format", "build", "_publish"]