
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-15T04:24:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d86f530afe4c40cf5aa993ffdfec80e9cf7e4eb",
 "version": "1.16.0.post.dev257"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
