
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-15T21:28:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16689028e56f77208931c59f18544d4f6ea3439b",
 "version": "0.0.65.post0.dev354"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
