
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T13:16:53+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a114fae395378f0718e3a6ae0ec047e3ae6f04ff",
 "version": "1.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
