# coding: utf-8

"""
    BIMData API

    BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@bimdata.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bimdata_api_client
from bimdata_api_client.models.raw_material_list import RawMaterialList  # noqa: E501
from bimdata_api_client.rest import ApiException

class TestRawMaterialList(unittest.TestCase):
    """RawMaterialList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RawMaterialList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bimdata_api_client.models.raw_material_list.RawMaterialList()  # noqa: E501
        if include_optional :
            return RawMaterialList(
                materials_data = [
                    bimdata_api_client.models.raw_material.RawMaterial(
                        id = 56, 
                        step_id = 56, 
                        name = '0', 
                        description = '0', 
                        category = '0', 
                        psets = [
                            56
                            ], )
                    ], 
                list_components = [
                    bimdata_api_client.models.raw_material_list_components.RawMaterialListComponents(
                        id = 56, 
                        material = 56, 
                        material_option = 56, )
                    ], 
                options = [
                    bimdata_api_client.models.raw_material_options.RawMaterialOptions(
                        id = 56, 
                        thickness = 1.337, 
                        material_list = [
                            56
                            ], )
                    ]
            )
        else :
            return RawMaterialList(
        )

    def testRawMaterialList(self):
        """Test RawMaterialList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
