# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.speech2text_pb2 as speech2text__pb2


class ASRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeStream = channel.stream_stream(
                '/ASR/TranscribeStream',
                request_serializer=speech2text__pb2.Audio.SerializeToString,
                response_deserializer=speech2text__pb2.Transcript.FromString,
                )
        self.TestStream = channel.stream_stream(
                '/ASR/TestStream',
                request_serializer=speech2text__pb2.Audio.SerializeToString,
                response_deserializer=speech2text__pb2.Transcript.FromString,
                )


class ASRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TranscribeStream,
                    request_deserializer=speech2text__pb2.Audio.FromString,
                    response_serializer=speech2text__pb2.Transcript.SerializeToString,
            ),
            'TestStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TestStream,
                    request_deserializer=speech2text__pb2.Audio.FromString,
                    response_serializer=speech2text__pb2.Transcript.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ASR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ASR/TranscribeStream',
            speech2text__pb2.Audio.SerializeToString,
            speech2text__pb2.Transcript.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ASR/TestStream',
            speech2text__pb2.Audio.SerializeToString,
            speech2text__pb2.Transcript.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
