
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T09:49:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ab2bd9b278650675fcab3bbba058b9f57566e75",
 "version": "1.16.0.post.dev206"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
