[tool.poetry]
name = "dataart-python"
version = "0.1.0"
description = ""
authors = ["sadra khamoshi <sadrakhamoshi7@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "2.27.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
