[tool.poetry]
name = "mpk"
version = "0.1.0.alpha4"
description = "Media Programming Kit Python bindings"
authors = [ "ellis <ellis@rwest.io>" ]
license = "WTF"
repository = "https://hg.rwest.io/mpk"
keywords = ["media", "Rust", "FFI", "audio"]
packages = [
  { include = "mpk", format = "sdist" },
  { include = "mpk_extract.py", format = "wheel" },
]

[tool.poetry.dependencies]
numpy = "^1.21"
essentia = "^2.1b6"
llvmlite = "^0.38.0"
librosa = "^0.9.1"
python = ">=3.7,<3.11"

[tool.poetry.dev-dependencies]
black = {version = ">=21", python = ">=3.9"}

[tool.poetry.scripts]
main = "mpk_extract:run"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'