[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"

[project]
name = "ipwhl"
version = "1.1.0"
description = "Utilities for the InterPlanetary Wheels"
readme = "README.md"
requires-python = ">=3.6"
license = { file = "COPYING" }
authors = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" } ]
maintainers = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" },
                { name = "Ngô Ngọc Đức Huy", email = "huyngo@disroot.org" } ]
keywords = [ "ipfs", "wheel", "packaging", "toml" ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: System :: Archiving :: Packaging",
    "Topic :: Utilities" ]
dependencies = [ "packaging", "tomli" ]
urls = { Source = "https://git.sr.ht/~cnx/ipwhl-utils" }

[project.scripts]
ipwhl-prefix = "ipwhl.prefix:main"
ipwhl-declgen = "ipwhl.declgen:main"
ipwhl-nameck = "ipwhl.nameck:main"
ipwhl-declck = "ipwhl.declck:main"
ipwhl-depsck = "ipwhl.depsck:main"
ipwhl-publish = "ipwhl.publish:main"
