
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T11:28:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a930ca144b028d026da96e4d484ce38b91a9a37",
 "version": "0.7.1.post.dev435"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
