
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-10T22:43:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a27c6183a23cf704160b11ff9a3795fc7a650ec1",
 "version": "0.0.67.post0.dev230"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
