[tool.poetry]
name = "fuckoff_denis"
version = "0.0.0"
description = "fuckoff"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
scipy = "^1.8.0"
numpy = "^1.22.3"
matplotlib = "^3.5.1"
sympy = "^1.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
