[tool.poetry]
name = "byugrid"
version = "0.1.1"
description = "2D grid, used for teaching people how to program"
authors = ["Daniel Zappala <daniel.zappala@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
