
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-14T11:31:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4deb113cb01d28588e5737e87071172a6cc8c36",
 "version": "4.12.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
