[tool.poetry]
name = "fastapi-another-jwt-auth"
version = "0.1.1"
description = ""
authors = ["Mariusz Masztalerczuk <mariusz@masztalerczuk.com>", "Nyoman Pradipta Dewantara <nyomanpradipta120@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
PyJWT = "^2.3.0"
fastapi = "^0.75.0"
cryptography = "^36.0.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
requests = "^2.27.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
