[tool.pytest.ini_options]
addopts = "--doctest-modules -x --nbmake"
usefixtures = "setup_tests_fixture"
doctest_optionflags = "NORMALIZE_WHITESPACE NUMBER ELLIPSIS IGNORE_EXCEPTION_DETAIL"


[tool.black]
line-length = 110
