[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.1,<4"]

[tool.flit.metadata]
module = "jupyterlite"
author = "JupyterLite Contributors"
author-email = ""
description-file = "README.md"
license = "BSD-3-Clause"
home-page = "https://github.com/jupyterlite/jupyterlite"
requires-python = ">=3.7"
requires = [
    "doit",
    "entrypoints",
    "jupyter_core >=4.7",
]
keywords = "jupyterlab,jupyter,notebook,schema,pyodide,browser,js,p5.js,doit"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Jupyter",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Pre-processors",
    "Topic :: Text Processing :: Markup :: HTML",
]

[tool.flit.scripts]
jupyter-lite = "jupyterlite.app:main"

[tool.flit.sdist]
include = [
    "src/jupyterlite/jupyterlite-*.tgz",
]

[tool.flit.metadata.requires-extra]
test = [
    "ansi2html",
    "diffoscope; sys_platform == 'linux'",
    "pytest-console-scripts",
    "pytest-cov",
    "pytest-html",
    "pytest-xdist",
]
lab = [
    "jupyterlab >=3.1,<4",
]
contents = [
    "jupyter_server",
]
translation = [
    "jupyterlab_server >=2.8.1,<3",
]
serve = [
    "tornado >=6.1",
]
piplite = [
    "pkginfo"
]
mathjax = [
    "jupyter-server-mathjax >=0.2.3",
]
check = [
    "jsonschema[format_nongpl] >=3",
]
all = [
    "jsonschema >=3",
    "jupyter_server",
    "jupyter-server-mathjax >=0.2.3",
    "jupyterlab >=3.0,<4",
    "jupyterlab_server >=2.8.1,<3",
    "pkginfo",
    "tornado >=6.1",
]

[tool.flit.entrypoints."jupyterlite.addon.v0"]
static = "jupyterlite.addons.static:StaticAddon"
federated_extensions = "jupyterlite.addons.federated_extensions:FederatedExtensionAddon"
settings = "jupyterlite.addons.settings:SettingsAddon"
contents = "jupyterlite.addons.contents:ContentsAddon"
translation = "jupyterlite.addons.translation:TranslationAddon"
lite = "jupyterlite.addons.lite:LiteAddon"
report = "jupyterlite.addons.report:ReportAddon"
serve = "jupyterlite.addons.serve:ServeAddon"
archive = "jupyterlite.addons.archive:ArchiveAddon"
piplite = "jupyterlite.addons.piplite:PipliteAddon"
pyodide = "jupyterlite.addons.pyodide:PyodideAddon"
mathjax = "jupyterlite.addons.mathjax:MathjaxAddon"

[tool.pytest.ini_options]
filterwarnings = [
    # https://github.com/jupyter-server/jupyter_server_mathjax/pull/11
    "ignore:.*Use `_i18n\\(\\)`.*:FutureWarning",
]
