
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-18T11:10:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b90d17ce2872a0f3c9b75d7304a185c9205e8ee",
 "version": "0.7.1.post.dev437"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
