[tool.poetry]
name = "fineas"
version = "1.0.1"
description = "A simple, decorator-based, transition-focused Finite State Machine implementation."
authors = ["Chris Blades"]
license = "Apache 2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.2"
wrapt = "^1.14.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
