[tool.poetry]
name = "django-fiction-outlines-api"
version = "0.3.0"
description = "A RESTful JSON API for django-fiction-outlines."
authors = ["Daniel Andrlik <daniel@andrlik.org>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.9"
django-fiction-outlines = "^0.4.0"
djangorestframework = "^3.13.1"
django-rest-framework-rules = "^1.0.0"
coreapi = "^2.3.3"
Markdown = "^3.3.6"
django-filter = "^21.1"
dj-taggit-serializer = "^0.1.7"
six = "^1.16.0"

[tool.poetry.dev-dependencies]
django-test-plus = "^2.2.0"
coverage = "^6.3.2"
mock = "^4.0.3"
flake8 = "^4.0.1"
pytest-django = "^4.5.2"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"
pytest-xdist = "^2.5.0"
pytest-flake8 = "^1.1.0"
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
