
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T18:19:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "27ce3166697d0e0bd01b32f144111a23ebcea9af",
 "version": "1.16.0.post.dev218"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
