[tool.poetry]
name = "pymosru"
version = "1.0.0"
description = ""
authors = ["yer7700"]
packages = [
    { include = "mosru.py" }
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
