
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T14:25:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab49db91c45505bf3c1b1b3795637a294d7987ca",
 "version": "0.0.67.post0.dev325"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
