#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from ..input.resource_specification_relation_ship_list_input import ResourceSpecificationRelationShipListInput


@dataclass(frozen=True)
class AddResourceSpecificationRelationShipListInput(DataClassJsonMixin):
    resourceSpecification: str
    nameList: List[ResourceSpecificationRelationShipListInput]
