[tool.poetry]
name = "packup"
version = "0.1.0"
description = "A full-fledged Python/C-Extension packaging frontend for humans"
authors = ["Adam Hendry <adam.grant.hendry@gmail.com>"]
license = "Apache-2.0"
packages = [
    { include = "packup" },
    { include = "docs" },
    { include = "tests" }
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Build Tools"
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
twine = "^3.8.0"
Sphinx = "^4.4.0"
black = "^22.1.0"
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.1.13"]
build-backend = "poetry.core.masonry.api"
