[tool.poetry]
name = "abi_ds_utils"
version = "0.1.1"
description = "Utility modules for working with mlflow, containers, aws and many more."
authors = ["Martin Matousek"]
license = "Private"

[tool.poetry.dependencies]
python = "3.8.8"
boto3 = "^1.21.14"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
