
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-10T18:58:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd5c5b0daf4225e85be8719ac6ae3f4ad82c5c29",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
