
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T13:46:46-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c6a5e03d94e83058fe18a6c79f7c13df30cf3fc",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
