---
- fail:
    msg: >
      Unsupported operating system;
      {{ ansible_distribution }}-{{ ansible_distribution_version }},
      {{ ansible_distribution }}-{{ ansible_distribution_major_version }},
      {{ ansible_distribution }},
      {{ ansible_os_family }}
