# Generated by Django 2.2.27 on 2022-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0003_auto_20220309_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Question required'),
        ),
    ]
