
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T10:26:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "954a5b8f3c57fdf856ed579eb8c7de7d69d348e6",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
