
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T16:16:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9670e744b35a164ebd6cc0bc18ce7411f2827ad",
 "version": "5.0.0-a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
