[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pydamain"
authors = [{name = "by-Exist", email = "bolk9652@naver.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">= 3.10"
dependencies = [
    "pydantic ~= 1.9",
    "orjson   ~= 3.6",
]

[project.urls]
Home = "https://github.com/by-Exist/pydamain"

[project.optional-dependencies]
test = [
    "pytest         ~= 6.2",
    "pytest-asyncio ~= 0.18"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"