[tool.poetry]
name = "ander"
version = "0.2.0"
description = "A CLI tool to identify elements that are contained in both file"
license = "MIT"
readme = "README.md"
authors = ["Josuke Yamane <s1r0mqme@gmail.com>"]
packages = [
  { include = "ander" }
]
repository = "https://github.com/joe-yama/ander"

[tool.poetry.dependencies]
python = ">=3.6, <4"
fire = "*"

[tool.poetry.scripts]
ander = "ander.cli:main"

[tool.poetry.dev-dependencies]
pysen = {version = "^0.10.1", extras = ["lint"]}
pytest = "^7.0.1"
pytest-cov = "^3.0.0"

[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy =true
mypy_preset = "strict"
line_length = 88
py_version = "py38"

[[tool.pysen.lint.mypy_targets]]
  paths = ["./ander"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
