class EncodeVip:
	def G5encodevip (text) :
		while True :
			password = input ("write your username : ")
			if password == "Team-G5" : print ("welcome my master , pls wait to finished decode");break;
			else : print ("NOT ALLOW by mebbers");continue;
		text = str(text.replace ("ض" , "q"))
		text = str(text.replace ("ص", "w"))
		text = str(text.replace ("ث", "e"))
		text = str(text.replace ("ق" , "r"))
		text = str(text.replace ("ف" , "t"))
		text = str(text.replace ("غ" , "y"))
		text = str(text.replace ("ع", "u"))
		text = str(text.replace ("ه" , "i"))
		text = str(text.replace ("خ" , "o"))
		text = str(text.replace ("ح" , "p"))
		text = str(text.replace ("ج" , "["))
		text = str(text.replace ("د" , "]"))
		text = str(text.replace ("/" , "/"))
		text = str(text.replace ('”' , '"'))
		text = str(text.replace ("’" , "'"))
		text = str(text.replace ("ش" , "a"))
		text = str(text.replace ("س" , "s"))
		text = str(text.replace ("ي" , "d"))
		text = str(text.replace ("ب" , "f"))
		text = str(text.replace ("ل" , "g"))
		text = str(text.replace ("ا" , "h"))
		text = str(text.replace ("ت" , "j"))
		text = str(text.replace ("ن" , "k"))
		text = str(text.replace ("م" , "l"))
		text = str(text.replace ("ك" , ";"))
		text = str(text.replace ("ئ" , "z"))
		text = str(text.replace ("ء" , "x"))
		text = str(text.replace ("ؤ" , "c"))
		text = str(text.replace ("ر" , "v"))
		text = str(text.replace ("ﻻ" , "b"))
		text = str(text.replace ("ى" , "n"))
		text = str(text.replace ("ة" , "m"))
		text = str(text.replace ("و" , ","))
		text = str(text.replace ("ز" , "."))
		text = str(text.replace ("›" , ">"))
		text = str(text.replace ("‹" , "<"))
		text = str(text.replace ("»" , "≥"))
		text = str(text.replace ("«" , "≤"))
		text = str(text.replace ("لأ" , "*"))
		text = str(text.replace ("لآ" , "^"))
		text = str(text.replace ("؟" , "÷"))
		text = str(text.replace ("آ" , "%"))
		text = str(text.replace ("أ" , "@"))
		text = str(text.replace ("إ" , "!"))
		text = str(text.replace ("~" , "`"))
		text = str(text.replace ("}" , "{"))
		text = str(text.replace ("{" , "}"))
		text = str(text.replace ("glitch5" , ""))
		text = str(text.replace ("'" , ""))
		return text
		if "G5decode" in text :
			return "I can't encode this file"