[tool.poetry]
name = "cran-diff"
version = "0.1.16"
description = ""
authors = ["Myles Mitchell <myles@jumpingrivers.com>", "Aoife Curran <aocurran@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "*"
deb_pkg_tools = "*"
python-dateutil = "*"
bs4 = "*"
requests = "*"
psycopg2-binary = "*"
tqdm = "*"
pandas = "*"
scipy = "*"
typing = "*"
rpy2 = "*"
requests-file = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.7b0"
flake8 = "^3.9.1"
pylint = "^2.7.4"
mypy = "^0.812"
pytest-datadir = "^1.3.1"
requests-mock = "^1.9.3"
freezegun = "^1.1.0"
coverage = "^5.5"
pytest-cov = "^2.12.1"
pre-commit = "^2.17.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
