[tool.poetry]
name = "thunderstruck"
version = "0.0.1"
description = "CDP based on ray.io"
authors = ["Data Platform <data.platform@typeform.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/afranzi/thunderstruck"
homepage = "https://github.com/afranzi/thunderstruck"

[tool.poetry.dependencies]
python = "^3.8"
ray = "^1.11.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
flake8 = "^4.0.1"
tox = "^3.24.5"
mypy = "^0.930"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
