_target_: nlhappy.datamodules.SentencePairDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
pretrained_dir: ${pretrained_dir}
dataset: 
pretrained_model: 
max_length: 
batch_size: 
return_sentence_pair: False
num_workers: 2
pin_memory: True