_target_: nlhappy.datamodules.SpanClassificationDataModule


dataset: 
max_length: 
batch_size:
plm: chinese-macbert-base 
pin_memory: True
num_workers: 2
data_dir: ${data_dir}
pretrained_dir: ${pretrained_dir}
