[tool.poetry]
name = "charmonium.determ_hash"
version = "0.2.2"
description = ""
authors = ["Samuel Grayson <grayson5@illinois.edu>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/charmoniumQ/charmonium.determ_hash.git"
packages = [
    { include = "charmonium" },
]
keywords = ["deterministic", "hash"]
classifiers = [
			"Development Status :: 4 - Beta",
			"Operating System :: OS Independent",
			"Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = "^3.7"
# make sure to keep the Python versions here consistent with those tested by Tox (tool.tox.legacy_tox_ini.tox.envlist).
xxhash = "^2.0.2"

[tool.poetry.dev-dependencies]
# For ./script.py fmt
autoimport = "^0.7.5"
isort = "^5.10.0"
black = "^21.10b0"
pylint = "^2.11.1"

# For ./script.py test
mypy = "^0.910"
pytest = "^6.2.5"

# Runs pytest in parallel
pytest-xdist = "^2.4.0"

# For coverage
pytest-cov = "^3.0.0"
coverage = "^6.1.2"

# For ./script.py all-tests
tox = "^3.24.4"
radon = "^5.1.0"
twine = "^3.5.0"
proselint = "^0.13.0"
rstcheck = "^3.3.1"

# For ./script.py publish
bump2version = "^1.0.1"

# For ./script.py
"charmonium.async-subprocess" = "^0.1.7"
typer = "^0.4.0"
termcolor = "^1.1.0"
typing-extensions = "^4.1.1"

# For debugging
ipython = "^7.29.0"
ipdb = "^0.13.9"

# rest

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--quiet --numprocesses=auto --doctest-modules --doctest-glob='*.rst'"

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    'pragma: no cover',
    'def __repr__',
    'if self\.debug',
    'raise AssertionError',
    'raise NotImplementedError',
    'if False:',
    'if __name__ == .__main__.:',
	'if TYPE_CHECKING',
    '@(abc\.)?abstractmethod',
    '\w*\.\.\.$',
    '\w*pass$',
]

# [tool.pylint]
# Too long for inclusion here
# see pylintrc

[tool.mypy]
strict = true
pretty = true
error_summary = true
color_output = true
disable_error_code = "no-redef"
#mypy_path = stubs

[tool.bump2version]
current_version = "0.2.2"
commit = true
tag = true

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{37,38,39,310}
# Make sure to install the Python versions listed here in the Nix flake.
isolated_build = True

[testenv]
whitelist_externals = poetry
skip_install = true
commands =
    poetry install
    {toxinidir}/script.py per-env-tests
"""
