[tool.poetry]
name = "deebee"
version = "0.0.0"
description = "A database funcions helper."
authors = ["Manasses Lima <manasseslima@gmail.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
