
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T04:27:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb1c282916aab77d5636fb8ae3295fc14d954154",
 "version": "1.16.0.post.dev262"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
