
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-15T11:23:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "26c9f5d282d36c97400548b34a4ade321d4b6644",
 "version": "0.7.1.post.dev425"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
