[tool.poetry]
name = "first-step"
version = "0.1.0"
description = ""
authors = ["jasjung <insikjung2017@u.northwestern.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 95
target-version = [ "py39",]


[tool.poetry.scripts]
inc = "first_step.cli:cli"