[tool.poetry]
name = "bike"
version = "0.2.0"
description = "A lightweight model validator for modern projects."
authors = ["Manasses Lima <manasseslima@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/manasseslima/bike"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
