[tool.poetry]
name = "treesync"
version = "1.2.1"
description = "Utilitiies to use rsync for whole trees"
authors = ["Ilkka Tuohela <hile@iki.fi>"]
license = "PSF"

[tool.poetry.dependencies]
python = "^3.9"
pathlib-tree = "^2.1"

[tool.poetry.dev-dependencies]
coverage = "^6.1"
flake8 = "^4.0"
flake8-bugbear = "^21.9"
flake8-quotes = "^3.3"
pycodestyle = "^2.8"
pyflakes = "^2.4"
pylint = "^2.11"
pytest = "^6.2"
tox = "^3"

[tool.poetry.scripts]
treesync = "treesync.bin.treesync.main:main"

[build-system]
# requires = ["poetry-core"]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git@master"]
build-backend = "poetry.core.masonry.api"
