
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "stray"
authors = [{email = "hello@strayrobots.io"}]
dynamic = ["version", "description"]
