# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: featurestore/core/FeatureSetProtoApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='featurestore/core/FeatureSetProtoApi.proto',
  package='featurestore.core',
  syntax='proto3',
  serialized_options=b'\n\030ai.h2o.featurestore.coreB\027FeatureSetProtoApiProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*featurestore/core/FeatureSetProtoApi.proto\x12\x11\x66\x65\x61turestore.core\"[\n\x10\x46\x65\x61tureSetHeader\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x65\x61ture_set_id\x18\x02 \x01(\t\x12\x1b\n\x13\x66\x65\x61ture_set_version\x18\x03 \x01(\tB3\n\x18\x61i.h2o.featurestore.coreB\x17\x46\x65\x61tureSetProtoApiProtob\x06proto3'
)




_FEATURESETHEADER = _descriptor.Descriptor(
  name='FeatureSetHeader',
  full_name='featurestore.core.FeatureSetHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='featurestore.core.FeatureSetHeader.project_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_set_id', full_name='featurestore.core.FeatureSetHeader.feature_set_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_set_version', full_name='featurestore.core.FeatureSetHeader.feature_set_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['FeatureSetHeader'] = _FEATURESETHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureSetHeader = _reflection.GeneratedProtocolMessageType('FeatureSetHeader', (_message.Message,), {
  'DESCRIPTOR' : _FEATURESETHEADER,
  '__module__' : 'featurestore.core.FeatureSetProtoApi_pb2'
  # @@protoc_insertion_point(class_scope:featurestore.core.FeatureSetHeader)
  })
_sym_db.RegisterMessage(FeatureSetHeader)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
