[tool.poetry]
name = "piconard"
version = "0.0.1"
description = "Raspberrypi convert to Arduino"
authors = ["madscientist <eggo.world@gmail.com>"]
license = "MIT"
# homepage = "madscientist"


[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
start = "piconard:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
