#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class ResourceSpecificationItemsFilterType(Enum):
    RESOURCE_SPECIFICATION_RELATIONSHIP = "RESOURCE_SPECIFICATION_RELATIONSHIP"
    RESOURCE_SPECIFICATION = "RESOURCE_SPECIFICATION"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "ResourceSpecificationItemsFilterType":
        return cls.MISSING_ENUM
