[tool.poetry]
name = "devseed"
version = "0.1.5"
description = "Tool to seed database using YAML files"
authors = ["Edvard Majakari <edvard@majakari.net>"]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
funcy = "^1.17"
typer = "^0.4.0"
environs = "^9.5.0"
pendulum = "^2.1.2"
PyPika = "^0.48.8"
pg8000 = "^1.24.1"
rich = "^11.2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.931"
types-PyYAML = "^6.0.4"
pytest = "^7.0.1"
pytest-describe = "^2.0.1"
bumpver = "^2022.1115"
pytest-mock = "^3.7.0"
freezegun = "^1.2.0"
pytest-icdiff = "^0.5"
pytest-cov = "^3.0.0"
icecream = "^2.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
devseed = "devseed.devseed:app"

[tool.bumpver]
current_version = "0.1.5"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"devseed/__init__.py" = ['__version__ = "{version}"']
"README.md" = ["{version}"]
