
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T19:50:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "335afe336502b5d5e38ecc4b637c54e9d09a322e",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
