#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nasminer',
 'nasminer.dicom',
 'nasminer.edf',
 'nasminer.ixtrend',
 'nasminer.mict',
 'nasminer.syringes']

package_data = \
{'': ['*'], 'nasminer': ['odm/*']}

install_requires = \
['numpy>=1.21.4',
 'pandas>=1.3.4',
 'SQLAlchemy>=1.4.26',
 'psycopg2>=2.9.1',
 'puremagic>=1.11',
 'pydicom>=2.2.2',
 'pyEDFlib>=0.1.22',
 'python-dateutil>=2.8.2',
 'Levenshtein>=0.16.0',
 'openpyxl>=3.0.9']

setup(name='nasminer',
      version='2022.3.14',
      description='Mine the NAS.',
      author='Jona JOACHIM',
      author_email='jona@joachim.cc',
      url='https://framagit.org/jaj/nasminer',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
