# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/mining/v1/adu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n arg_services/mining/v1/adu.proto\x12\x16\x61rg_services.mining.v1\"p\n\x13SegmentationRequest\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x45\n\x0bgranularity\x18\x02 \x01(\x0e\x32#.arg_services.mining.v1.GranularityR\x0bgranularity\"2\n\x14SegmentationResponse\x12\x1a\n\x08segments\x18\x01 \x03(\tR\x08segments\"w\n\x15\x43lassificationRequest\x12\x1a\n\x08segments\x18\x01 \x03(\tR\x08segments\x12\x42\n\nclassifier\x18\x02 \x01(\x0e\x32\".arg_services.mining.v1.ClassifierR\nclassifier\"_\n\x16\x43lassificationResponse\x12\x45\n\x08segments\x18\x01 \x03(\x0b\x32).arg_services.mining.v1.ClassifiedSegmentR\x08segments\"i\n\x11\x43lassifiedSegment\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x10\n\x03\x61\x64u\x18\x02 \x01(\x08R\x03\x61\x64u\x12\x14\n\x05\x63laim\x18\x03 \x01(\x08R\x05\x63laim\x12\x18\n\x07premise\x18\x04 \x01(\x08R\x07premise*|\n\x0bGranularity\x12\x1b\n\x17GRANULARITY_UNSPECIFIED\x10\x00\x12\x18\n\x14GRANULARITY_SENTENCE\x10\x01\x12\x1b\n\x17GRANULARITY_SUBSENTENCE\x10\x02\x12\x19\n\x15GRANULARITY_PARAGRAPH\x10\x03*u\n\nClassifier\x12\x1a\n\x16\x43LASSIFIER_UNSPECIFIED\x10\x00\x12\x16\n\x12\x43LASSIFIER_TWO_WAY\x10\x01\x12\x18\n\x14\x43LASSIFIER_THREE_WAY\x10\x02\x12\x19\n\x15\x43LASSIFIER_SEQUENTIAL\x10\x03\x32\xe8\x01\n\nAduService\x12i\n\x0cSegmentation\x12+.arg_services.mining.v1.SegmentationRequest\x1a,.arg_services.mining.v1.SegmentationResponse\x12o\n\x0e\x43lassification\x12-.arg_services.mining.v1.ClassificationRequest\x1a..arg_services.mining.v1.ClassificationResponseB\xab\x01\n)de.uni_trier.recap.arg_services.mining.v1B\x08\x41\x64uProtoP\x01\xa2\x02\x03\x41MX\xaa\x02\x15\x41rgServices.Mining.V1\xca\x02\x15\x41rgServices\\Mining\\V1\xe2\x02!ArgServices\\Mining\\V1\\GPBMetadata\xea\x02\x17\x41rgServices::Mining::V1b\x06proto3')

_GRANULARITY = DESCRIPTOR.enum_types_by_name['Granularity']
Granularity = enum_type_wrapper.EnumTypeWrapper(_GRANULARITY)
_CLASSIFIER = DESCRIPTOR.enum_types_by_name['Classifier']
Classifier = enum_type_wrapper.EnumTypeWrapper(_CLASSIFIER)
GRANULARITY_UNSPECIFIED = 0
GRANULARITY_SENTENCE = 1
GRANULARITY_SUBSENTENCE = 2
GRANULARITY_PARAGRAPH = 3
CLASSIFIER_UNSPECIFIED = 0
CLASSIFIER_TWO_WAY = 1
CLASSIFIER_THREE_WAY = 2
CLASSIFIER_SEQUENTIAL = 3


_SEGMENTATIONREQUEST = DESCRIPTOR.message_types_by_name['SegmentationRequest']
_SEGMENTATIONRESPONSE = DESCRIPTOR.message_types_by_name['SegmentationResponse']
_CLASSIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['ClassificationRequest']
_CLASSIFICATIONRESPONSE = DESCRIPTOR.message_types_by_name['ClassificationResponse']
_CLASSIFIEDSEGMENT = DESCRIPTOR.message_types_by_name['ClassifiedSegment']
SegmentationRequest = _reflection.GeneratedProtocolMessageType('SegmentationRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTATIONREQUEST,
  '__module__' : 'arg_services.mining.v1.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1.SegmentationRequest)
  })
_sym_db.RegisterMessage(SegmentationRequest)

SegmentationResponse = _reflection.GeneratedProtocolMessageType('SegmentationResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTATIONRESPONSE,
  '__module__' : 'arg_services.mining.v1.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1.SegmentationResponse)
  })
_sym_db.RegisterMessage(SegmentationResponse)

ClassificationRequest = _reflection.GeneratedProtocolMessageType('ClassificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONREQUEST,
  '__module__' : 'arg_services.mining.v1.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1.ClassificationRequest)
  })
_sym_db.RegisterMessage(ClassificationRequest)

ClassificationResponse = _reflection.GeneratedProtocolMessageType('ClassificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONRESPONSE,
  '__module__' : 'arg_services.mining.v1.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1.ClassificationResponse)
  })
_sym_db.RegisterMessage(ClassificationResponse)

ClassifiedSegment = _reflection.GeneratedProtocolMessageType('ClassifiedSegment', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFIEDSEGMENT,
  '__module__' : 'arg_services.mining.v1.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1.ClassifiedSegment)
  })
_sym_db.RegisterMessage(ClassifiedSegment)

_ADUSERVICE = DESCRIPTOR.services_by_name['AduService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)de.uni_trier.recap.arg_services.mining.v1B\010AduProtoP\001\242\002\003AMX\252\002\025ArgServices.Mining.V1\312\002\025ArgServices\\Mining\\V1\342\002!ArgServices\\Mining\\V1\\GPBMetadata\352\002\027ArgServices::Mining::V1'
  _GRANULARITY._serialized_start=551
  _GRANULARITY._serialized_end=675
  _CLASSIFIER._serialized_start=677
  _CLASSIFIER._serialized_end=794
  _SEGMENTATIONREQUEST._serialized_start=60
  _SEGMENTATIONREQUEST._serialized_end=172
  _SEGMENTATIONRESPONSE._serialized_start=174
  _SEGMENTATIONRESPONSE._serialized_end=224
  _CLASSIFICATIONREQUEST._serialized_start=226
  _CLASSIFICATIONREQUEST._serialized_end=345
  _CLASSIFICATIONRESPONSE._serialized_start=347
  _CLASSIFICATIONRESPONSE._serialized_end=442
  _CLASSIFIEDSEGMENT._serialized_start=444
  _CLASSIFIEDSEGMENT._serialized_end=549
  _ADUSERVICE._serialized_start=797
  _ADUSERVICE._serialized_end=1029
# @@protoc_insertion_point(module_scope)
