# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['zhenxun_bot',
 'zhenxun_bot.basic_plugins',
 'zhenxun_bot.basic_plugins.admin_bot_manage',
 'zhenxun_bot.basic_plugins.admin_help',
 'zhenxun_bot.basic_plugins.apscheduler',
 'zhenxun_bot.basic_plugins.ban',
 'zhenxun_bot.basic_plugins.broadcast',
 'zhenxun_bot.basic_plugins.group_handle',
 'zhenxun_bot.basic_plugins.help',
 'zhenxun_bot.basic_plugins.hooks',
 'zhenxun_bot.basic_plugins.init_plugin_config',
 'zhenxun_bot.basic_plugins.invite_manager',
 'zhenxun_bot.basic_plugins.shop',
 'zhenxun_bot.basic_plugins.shop.shop_handle',
 'zhenxun_bot.basic_plugins.shop.use',
 'zhenxun_bot.basic_plugins.super_cmd',
 'zhenxun_bot.basic_plugins.super_help',
 'zhenxun_bot.configs',
 'zhenxun_bot.configs.utils',
 'zhenxun_bot.models',
 'zhenxun_bot.plugins',
 'zhenxun_bot.plugins.aconfig',
 'zhenxun_bot.plugins.ai',
 'zhenxun_bot.plugins.alapi',
 'zhenxun_bot.plugins.bilibili_sub',
 'zhenxun_bot.plugins.black_word',
 'zhenxun_bot.plugins.bt',
 'zhenxun_bot.plugins.check',
 'zhenxun_bot.plugins.check_zhenxun_update',
 'zhenxun_bot.plugins.coser',
 'zhenxun_bot.plugins.dialogue',
 'zhenxun_bot.plugins.draw_card',
 'zhenxun_bot.plugins.draw_card.handles',
 'zhenxun_bot.plugins.epic',
 'zhenxun_bot.plugins.genshin',
 'zhenxun_bot.plugins.genshin.almanac',
 'zhenxun_bot.plugins.genshin.material_remind',
 'zhenxun_bot.plugins.genshin.query_resource_points',
 'zhenxun_bot.plugins.genshin.query_user',
 'zhenxun_bot.plugins.genshin.query_user._models',
 'zhenxun_bot.plugins.genshin.query_user._utils',
 'zhenxun_bot.plugins.genshin.query_user.bind',
 'zhenxun_bot.plugins.genshin.query_user.genshin_sign',
 'zhenxun_bot.plugins.genshin.query_user.query_memo',
 'zhenxun_bot.plugins.genshin.query_user.query_role',
 'zhenxun_bot.plugins.genshin.query_user.reset_today_query_user_data',
 'zhenxun_bot.plugins.genshin.query_user.resin_remind',
 'zhenxun_bot.plugins.gold_redbag',
 'zhenxun_bot.plugins.group_last_chat',
 'zhenxun_bot.plugins.image_management',
 'zhenxun_bot.plugins.image_management.delete_image',
 'zhenxun_bot.plugins.image_management.move_image',
 'zhenxun_bot.plugins.image_management.send_image',
 'zhenxun_bot.plugins.image_management.upload_image',
 'zhenxun_bot.plugins.luxun',
 'zhenxun_bot.plugins.music',
 'zhenxun_bot.plugins.my_info',
 'zhenxun_bot.plugins.one_friend',
 'zhenxun_bot.plugins.open_cases',
 'zhenxun_bot.plugins.open_cases.models',
 'zhenxun_bot.plugins.pix_gallery',
 'zhenxun_bot.plugins.pix_gallery._model',
 'zhenxun_bot.plugins.pixiv_rank_search',
 'zhenxun_bot.plugins.poke',
 'zhenxun_bot.plugins.russian',
 'zhenxun_bot.plugins.search_anime',
 'zhenxun_bot.plugins.search_buff_skin_price',
 'zhenxun_bot.plugins.search_image',
 'zhenxun_bot.plugins.send_dinggong_voice',
 'zhenxun_bot.plugins.send_setu_',
 'zhenxun_bot.plugins.send_setu_.send_setu',
 'zhenxun_bot.plugins.send_setu_.update_setu',
 'zhenxun_bot.plugins.sign_in',
 'zhenxun_bot.plugins.statistics',
 'zhenxun_bot.plugins.translate',
 'zhenxun_bot.plugins.update_gocqhttp',
 'zhenxun_bot.plugins.weather',
 'zhenxun_bot.plugins.what_anime',
 'zhenxun_bot.plugins.word_bank',
 'zhenxun_bot.plugins.yiqing',
 'zhenxun_bot.services',
 'zhenxun_bot.utils',
 'zhenxun_bot.utils.manager']

package_data = \
{'': ['*'],
 'zhenxun_bot': ['data/*',
                 'data/black_word/*',
                 'data/configs/*',
                 'data/custom_welcome_msg/*',
                 'data/draw_card/*',
                 'data/draw_card/draw_card_config/*',
                 'data/draw_card/draw_card_up/*',
                 'data/manager/*',
                 'data/statistics/*',
                 'data/word_bank/863633108/*']}

install_requires = \
['ImageHash>=4.2.1,<5.0.0',
 'Pillow>=9.0.1,<10.0.0',
 'PyYAML==5.4.1',
 'aiofiles>=0.8.0,<0.9.0',
 'aiohttp==3.7.4.post0',
 'beautifulsoup4==4.9.3',
 'bilibili-api>=9.1.0,<10.0.0',
 'black>=22.1.0,<23.0.0',
 'cn2an>=0.5.16,<0.6.0',
 'dateparser>=1.1.0,<2.0.0',
 'feedparser>=6.0.8,<7.0.0',
 'gino>=1.0.1,<2.0.0',
 'httpx>=0.22.0,<0.23.0',
 'jieba>=0.42.1,<0.43.0',
 'lxml==4.6.5',
 'matplotlib>=3.5.1,<4.0.0',
 'nonebot-adapter-onebot>=2.0.0-beta.1,<3.0.0',
 'nonebot-plugin-apscheduler>=0.1.2,<0.2.0',
 'nonebot2>=2.0.0-beta.2,<3.0.0',
 'opencv-python>=4.5.5,<5.0.0',
 'playwright>=1.18.2,<2.0.0',
 'psutil>=5.9.0,<6.0.0',
 'pypinyin>=0.46.0,<0.47.0',
 'retrying>=1.3.3,<2.0.0',
 'ruamel.yaml>=0.17.21,<0.18.0',
 'ujson>=5.1.0,<6.0.0']

setup_kwargs = {
    'name': 'zhenxun-bot',
    'version': '0.1.4.3',
    'description': '基于 Nonebot2 和 go-cqhttp 开发，以 postgresql 作为数据库，非常可爱的绪山真寻bot',
    'long_description': None,
    'author': 'HibiKier',
    'author_email': '775757368@qq.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
