[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = 'boltlight'
version = '2.1.0'
description = 'Lightning Network node wrapper'
license = 'AGPL-3.0-or-later'
authors = ['Hashbeam <hashbeam@protonmail.com>']
readme = 'README.md'
homepage = 'https://hashbeam.gitlab.io/boltlight'
repository = 'https://gitlab.com/hashbeam/boltlight'
documentation = 'https://hashbeam.gitlab.io/boltlight-doc'
keywords = ['lightning network', 'node', 'wrapper', 'bitcoin']
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Operating System :: MacOS',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Topic :: Other/Nonlisted Topic',
]

[tool.poetry.dependencies]
python = "^3.9.0"
alembic = "^1.5.5"
click = "^8.0.4"
googleapis-common-protos = "^1.53.0"
grpcio = "^1.43.0"
lnd-proto = "0.13.3-beta.0"
macaroonbakery = "^1.3.1"
protobuf = "^3.19.1"
pylibscrypt = "^1.8.0"
pyln-client = "0.10.1"
pymacaroons = "^0.13.0"
pynacl = "^1.3.0"
qrcode = "^6.1"
requests = "^2.25.1"
sqlalchemy = "~1.3.23"

[tool.poetry.dev-dependencies]
docutils = "^0.18.1"
grpcio-tools = "^1.43.0"
isort = "^5.10.1"
pylint = "^2.11.1"
pylint-protobuf = "^0.20.2"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
tox = "^3.24.4"
tox-factor = "^0.1.2"
yapf = "^0.32.0"

[tool.poetry.scripts]
blink = 'boltlight.blink:entrypoint'
boltlight = 'boltlight.boltlight:start'
boltlight-pairing = 'boltlight.pairing:start'
boltlight-secure = 'boltlight.secure:secure'

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
dynamic_context = 'test_function'
omit = ['*/*_pb2*.py', '*/migrate.py', '*/secure.py', '*/pairing.py',
        '*/migrations/*', '*/blink.py', '*/__init__.py', '*/settings.py']
parallel = true

[tool.isort]
filter_files = true
include_trailing_comma = false
multi_line_output = 4
skip = ['boltlight/boltlight_pb2.py', 'boltlight/boltlight_pb2_grpc.py']

[tool.yapf]
based_on_style = 'pep8'
split_penalty_import_names = 1000

[tool.yapfignore]
ignore_patterns = [
  'boltlight/boltlight_pb2.py',
  'boltlight/boltlight_pb2_grpc.py',
]
