[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = [
    "setuptools>=42",
	"wheel",
    "numpy",
	"pandas",
    "xlrd==1.2.0"

]
build-backend = "setuptools.build_meta"
