
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T10:17:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a7ccd32d8a557cfabdf5468c2be8380151ad7d6",
 "version": "1.16.0.post.dev208"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
