
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-13T08:35:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a0230de243d4b4bf21b6216c5f172a3b4075abf",
 "version": "7.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
