
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-11T16:01:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdf582c2a7972abed848b2e0d1574fbfebe15aa1",
 "version": "1.16.0.post.dev215"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
