[tool.poetry]
name = "rescrap"
version = "0.1.1"
description = "Regex Scraper"
authors = ["LouMa <louma.pypi@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
PyPDF2 = "^1.26.0"
regex = "^2021.11.10"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = {version = "^21.12b0", allow-prereleases = true}
mypy = {version = "^0.940", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
