[build-system]
requires = [
    "setuptools>=60",
    "build>=0.7.0",
    "pytest>=6.2.2",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]
