[tool.poetry]
name = "pyxstar"
version = "0.2.3"
description = "A library and commandline tool for managing Pix-Star digital photo frames"
keywords = ["pix-star", "pixstar"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/pgriess/pyxstar"
repository = "https://github.com/pgriess/pyxstar"
authors = ["Peter Griess <pg@std.in>"]

[tool.poetry.dependencies]
python = "^3.7"
lxml = "^4.5.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
mypy = "^0.931"
black = "^22.1.0"

[tool.poetry.scripts]
pyxstar = "pyxstar.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
