#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class ResourceSpecificationRelationshipFilterType(Enum):
    NAME = "NAME"
    RESOURCE_SPECIFICATION = "RESOURCE_SPECIFICATION"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "ResourceSpecificationRelationshipFilterType":
        return cls.MISSING_ENUM
