
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T11:55:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e3883befa7720fca510e675f220289ee6808833",
 "version": "0.4.117"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
