
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-12T03:01:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c96ef22db0909c7bf273b434c96d4d18df13fc6a",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
