from ._exceptions import LicenseError as LicenseError, ValidationError as ValidationError
from ._main import validate_license_key_cached as validate_license_key_cached
from ._offline_keys import validate_offline_key as validate_offline_key

def print_warning(msg) -> None: ...
def print_error(msg) -> None: ...
def validate(software_name: str, account_id: str, keygen_verify_key: str, product_id: str, refresh_cache_period=..., cache_age_warning=..., cache_age_error=..., expiry_warning=...) -> None: ...
