# coding: utf-8

"""
    BIMData API

    BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@bimdata.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bimdata_api_client
from bimdata_api_client.models.detailed_extensions import DetailedExtensions  # noqa: E501
from bimdata_api_client.rest import ApiException

class TestDetailedExtensions(unittest.TestCase):
    """DetailedExtensions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DetailedExtensions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bimdata_api_client.models.detailed_extensions.DetailedExtensions()  # noqa: E501
        if include_optional :
            return DetailedExtensions(
                topic_labels = [
                    bimdata_api_client.models.label.Label(
                        id = 56, 
                        label = '0', 
                        project = 56, )
                    ], 
                topic_types = [
                    bimdata_api_client.models.topic_type.TopicType(
                        id = 56, 
                        topic_type = '0', 
                        project = 56, )
                    ], 
                topic_statuses = [
                    bimdata_api_client.models.topic_status.TopicStatus(
                        id = 56, 
                        topic_status = '0', 
                        color = '0', 
                        project = 56, )
                    ], 
                priorities = [
                    bimdata_api_client.models.priority.Priority(
                        id = 56, 
                        priority = '0', 
                        color = '0', 
                        project = 56, )
                    ], 
                stages = [
                    bimdata_api_client.models.stage.Stage(
                        id = 56, 
                        stage = '0', 
                        project = 56, )
                    ]
            )
        else :
            return DetailedExtensions(
        )

    def testDetailedExtensions(self):
        """Test DetailedExtensions"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
