
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-15T14:41:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "53da0e66e2e3eb2361d6ec5003ee5373fc68d3ea",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
