[tool.poetry]
name = "badook-tests"
version = "0.4.0-pre.0"
description = "badook data testing framework for Python"
authors = ["badook Engineering <engineering@badook.ai>"]
license = "Apache License 2.0"
readme = "README.md"
homepage = "https://github.com/badook-ai/badook-tests-python"
repository = "https://github.com/badook-ai/badook-tests-python"

[tool.poetry.dependencies]
python = "~3.9.0"
websocket-client = "0.57.0"
cloudpickle = ">=1.6,<3.0"
click = "^8.0.1"
emoji = "^1.4.2"
Pysher = "^1.0.6"
shortuuid = "^1.0.1"
halo = "^0.0.31"
python-dateutil = "^2.8.2"
ipython = ">=7.27,<9.0"
requests = "^2.26.0"
pydantic = "^1.8.2"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
numpy = "^1.22.3"
scipy = "^1.8.0"
pre-commit = "^2.17.0"
pylint = "^2.12.2"
autopep8 = "^1.6.0"
pytest-dotenv = "^0.5.2"

[tool.pytest.ini_options]
norecursedirs = "tests/test_dir/*" # these tests are used by the airflow tests and need to be ignored by pytest

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "semver"
dirty = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=0.13.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bdk = 'badook_tests.cli.bdk:main'
