[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.isort]
known_first_party = "av2"
known_third_party = ""

line_length = 120
multi_line_output = 3
profile = "black"

[tool.mypy]
exclude = "build"
ignore_missing_imports = true
disallow_untyped_decorators = false
plugins = "numpy.typing.mypy_plugin"
strict = true
