[tool.poetry]
name = "CodeCraftOJ"
version = "0.2.0"
description = ""
authors = ["InEase <InEase28@gmail.com>"]
exclude = ["web"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
CodeCraftOJ = "CodeCraftOJ.cli:entry"
